version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
  kitchenrouter.webapi:
    image: ${DOCKER_REGISTRY-}kitchenrouterwebapi
    build:
      context: .
      dockerfile: KitchenRouter.WebAPI/Dockerfile
    depends_on:
      - rabbitmq